version: '3'
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    command: gin -p 8080
    ports:
      - 80:8080
    depends_on:
      - "db"

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE # 追加
    environment:
      MYSQL_ROOT_PASSWORD: go_wedding_pass_root_kkde5
      MYSQL_DATABASE: go_wedding_db
      MYSQL_USER: go_wedding_user
      MYSQL_PASSWORD: go_wedding_pass_kkde5
      # mysql -ugo_wedding_user -pgo_wedding_pass_kkde5
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306

volumes:
  db-data:
    driver: local